import { Route } from './route';
export const icons={arrow:'<svg viewBox="0 0 24 24" fill="none"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.5"/></svg>',play:'<svg viewBox="0 0 24 24" fill="none"><path d="m9 5 10 7-10 7V5Z" fill="currentColor"/></svg>',sun:'<svg viewBox="0 0 24 24" fill="none"><circle cx="12" cy="12" r="4" stroke="currentColor"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2" stroke="currentColor"/></svg>',pause:'<svg viewBox="0 0 24 24"><path d="M7 5h3v14H7zm7 0h3v14h-3z" fill="currentColor"/></svg>',camera:'<svg viewBox="0 0 24 24" fill="none"><path d="M3 7h5l2-3h4l2 3h5v13H3Z" stroke="currentColor"/><circle cx="12" cy="13" r="4" stroke="currentColor"/></svg>'};
export function mapSVG(route:Route,id='route-dot') {
  const pts=route.points.filter((_,i)=>i%8===0);const xs=pts.map(p=>p.x),zs=pts.map(p=>p.z),minX=Math.min(...xs),minZ=Math.min(...zs),scale=150/Math.max(Math.max(...xs)-minX,Math.max(...zs)-minZ);
  const path=pts.map((p,i)=>`${i?'L':'M'}${20+(p.x-minX)*scale},${15+(p.z-minZ)*scale}`).join(' ')+' Z';
  return {markup:`<svg viewBox="0 0 190 185" class="route-map" aria-label="Alpine loop route map"><path d="${path}" fill="none" stroke="currentColor" stroke-opacity=".15" stroke-width="8"/><path d="${path}" fill="none" stroke="currentColor" stroke-opacity=".72" stroke-width="1.3"/><circle id="${id}-target" cx="0" cy="0" r="5" fill="none" stroke="#d3edb6" stroke-width="1.5" style="display:none"/><circle id="${id}" cx="${20-minX*scale}" cy="${15-minZ*scale}" r="4" fill="#e4b977" stroke="#202a27" stroke-width="2"/></svg>`,minX,minZ,scale};
}
export function buildUI(route:Route){
 const map=mapSVG(route);
 document.querySelector('#app')!.innerHTML=`
 <div id="canvas-host"></div><div class="vignette"></div>
 <div id="loading" class="loading"><div class="brand">PORSCHE</div><div class="loading-title">A different kind of escape.</div><div class="load-track"><div id="load-bar"></div></div><p id="load-status">PREPARING YOUR PORSCHE</p><small>ALPINE DRIVE &nbsp; / &nbsp; VOLUME 01</small></div>
 <section id="menu" class="screen hidden">
  <div class="menu-shade"></div>
  <header class="header"><a class="brand home-link" href="#" aria-label="Porsche Alpine Drive home">PORSCHE</a><div class="edition">ALPINE DRIVE<span>A DRIVER’S EXPERIENCE</span></div><nav aria-label="Main navigation"><button class="nav-button active" data-action="home">Drive</button><button class="nav-button" data-action="challenges">Challenges</button><button class="nav-button" data-action="garage">Garage</button><button class="nav-button" data-action="settings">Settings</button></nav><span class="header-mark">EST. 1948 <i></i></span></header>
  <main class="hero"><div class="eyebrow"><span class="short-line"></span> NO FINISH LINE. JUST FEELING.</div><h1>Find your<br>next <em>horizon.</em></h1><p>A Porsche. An open mountain road.<br>Nothing between you and the drive.</p><button class="primary start-drive" data-action="drive"><span>Start your engine</span>${icons.arrow}</button><div class="input-hint"><span class="key">W</span><span class="key">A</span><span class="key">S</span><span class="key">D</span><span>THE ROAD IS YOURS</span></div></main>
  <aside class="destination"><div class="destination-top"><span class="live-dot"></span> YOUR NEXT ESCAPE <span>01 / 01</span></div><h2>Col de Lumière</h2><p>THE FRENCH ALPS &nbsp; · &nbsp; FICTIONAL ROUTE</p>${mapSVG(route,'menu-dot').markup}<div class="destination-bottom"><span>1,842 <small>M ASL</small></span><span>${(route.length/1000).toFixed(1)} <small>KM LOOP</small></span></div></aside>
  <div class="car-caption"><span class="tiny-cross">+</span><span>THE ICON. REIMAGINED BY THE ROAD.</span><strong>Pure Porsche.</strong></div>
  <footer class="menu-footer"><div class="footer-location"><span class="coordinate">45°55′ N &nbsp; 06°52′ E</span><span>Somewhere worth getting lost.</span></div><button class="weather-pill" data-action="weather">${icons.sun}<span id="menu-weather">Golden hour</span><span class="tiny-arrow">⌄</span></button><div class="footer-right"><span class="live-dot"></span> BUILT FOR THE DRIVE <span class="sound-label">SOUND ON RECOMMENDED</span></div></footer>
 </section>
 <section id="hud" class="screen hidden"><header class="drive-header"><div class="brand">PORSCHE</div><div class="drive-title"><span id="activity-label">FREE DRIVE</span><strong>Col de Lumière</strong></div><div class="drive-tools"><button class="icon-button" data-action="photo" title="Photo mode (P)" aria-label="Photo mode">${icons.camera}</button><button class="icon-button" data-action="pause" title="Pause (Escape)" aria-label="Pause">${icons.pause}</button></div></header>
 <div id="challenge-hud" class="challenge-hud hidden"><div><span id="checkpoint-label">CHECKPOINT 01 / 06</span><strong id="timer">00:00.00</strong></div><div class="challenge-target"><span id="target-label">TARGET</span><strong id="target-value">02:45.00</strong></div><div class="progress-track"><i id="challenge-progress"></i></div></div>
 <div id="countdown"></div><div id="route-message"></div>
 <div class="minimap">${map.markup}<div><span class="live-dot"></span><span id="road-name">VALLÉE DU SOLEIL</span></div></div>
 <div class="speedometer"><div class="speed-top"><span id="drive-state">SPORT</span><span id="camera-name">CHASE</span></div><div class="speed-main"><div class="gear-box"><small>GEAR</small><b id="gear">1</b></div><strong id="speed">000</strong><span id="speed-unit">KM/H</span></div><div class="rpm-track"><div id="rpm-fill"></div><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="rpm-label"><span id="rpm">850 RPM</span><span>8 000</span></div></div>
 <div class="drive-bottom"><span><kbd>C</kbd> CAMERA</span><span><kbd>P</kbd> PHOTO</span><span><kbd>R</kbd> RESET</span><span><kbd>ESC</kbd> PAUSE</span><span id="controller-status"></span></div>
 <div id="touch-controls"><div><button data-touch="left" aria-label="Steer left">←</button><button data-touch="right" aria-label="Steer right">→</button></div><div><button data-touch="brake" aria-label="Brake and reverse">BRAKE</button><button data-touch="throttle" aria-label="Accelerate">GO</button></div></div>
 </section>
 <section id="garage" class="screen hidden"><header class="header"><div class="brand">PORSCHE</div><div class="edition">THE GARAGE<span>AN ICON, EVERY ANGLE.</span></div><button class="text-button" data-action="back">Back to the road <span>↗</span></button></header><div class="garage-title"><div class="eyebrow">ENGINEERED TO STIR THE SOUL</div><h1>Design.<br>Without compromise.</h1></div><div class="garage-panel"><span class="eyebrow">THE ORIGINAL PORSCHE</span><h2>Every line has a purpose.</h2><p>The supplied, textured Porsche model.<br>Preserved in its original finish.</p><div class="option-label">LIGHTING ENVIRONMENT</div><div class="segments" id="garage-weather"><button data-weather="Sunset" class="selected">Sunset</button><button data-weather="Clear">Clear</button><button data-weather="Overcast">Overcast</button></div><button class="secondary" data-action="garage-angle">Explore another angle ${icons.arrow}</button><div class="gesture">DRAG TO ROTATE &nbsp; · &nbsp; SCROLL TO EXPLORE</div></div><div class="garage-footer">FORM FOLLOWS FEELING. <span>01 / PORSCHE COLLECTION</span></div></section>
 <section id="photo" class="screen hidden"><header class="photo-header"><span class="eyebrow">PORSCHE &nbsp; / &nbsp; PHOTO STUDIO</span><button class="text-button" data-action="exit-photo">Return to drive <kbd>P</kbd></button></header><div id="photo-grid" class="photo-grid"><i></i><i></i><i></i><i></i></div><div class="photo-panel"><label>FOCAL LENGTH <input id="photo-fov" type="range" min="22" max="85" value="45"><span id="fov-value">45°</span></label><button class="text-button" data-action="grid">Rule of thirds</button><button class="primary" data-action="capture">Capture photograph ${icons.camera}</button><p>DRAG TO ORBIT · RIGHT-DRAG TO PAN · SCROLL TO ZOOM</p></div></section>
 <div id="modal" class="modal hidden" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-backdrop"></div><div class="modal-content"><button class="modal-close" data-action="close" aria-label="Close dialog">×</button><div id="modal-body"></div></div></div>
 <div id="toast" role="status"></div><div id="fade"></div>`;
 return map;
}
export const activities=[
 {id:'time',number:'01',name:'The alpine run',type:'TIME TRIAL',desc:'One road. One lap. Your perfect line.',target:'BEAT 03:30',start:0,checkpoints:[.12,.25,.39,.53,.68,.84,.98],limit:210},
 {id:'speed',number:'02',name:'Chasing the horizon',type:'SPEED RUN',desc:'Open it up on the valley straight.',target:'REACH 160 KM/H',start:.005,checkpoints:[.035,.068,.105],limit:160},
 {id:'corner',number:'03',name:'The art of the corner',type:'CORNERING',desc:'Summit switchbacks. Precision over power.',target:'BEAT 00:45 · STAY CLEAN',start:.285,checkpoints:[.31,.34,.38,.42],limit:45},
 {id:'scenic',number:'04',name:'Take the long way',type:'SCENIC DRIVE',desc:'Cross the viaduct. Find the summit. Exhale.',target:'NO TIMER. NO PRESSURE.',start:.14,checkpoints:[.20,.29,.38,.49],limit:0}
];
